# Generated by Django 3.0.8 on 2020-08-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sepehr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address_rnd',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='session_id',
        ),
    ]
